Given a bank customer, build a neural network-based classifier that can determine
whether they will leave or not in the next 6 months.
Dataset Description: The case study is from an open-source dataset from
Kaggle.The dataset contains 10,000 sample points with 14 distinct features
such as CustomerId, CreditScore, Geography, Gender, Age, Tenure, Balance,
etc.
Link to the Kaggle project:
https://www.kaggle.com/barelydedicated/bank-customer-churnmodeling Perform following steps:
1. Read the dataset.
2. Distinguish the feature and target set and divide the data set into training and test
sets.
3. Normalize the train and test data.
4. Initialize and build the model. Identify the points of improvement and implement the
same.
Print the accuracy score and confusion matrix (5 points).

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Tanmay49/SEM7/main/ML/Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [5]:
gender = pd.get_dummies(df['Gender'],drop_first=True)
geography = pd.get_dummies(df['Geography'],drop_first=True)
df = pd.concat([df,gender,geography],axis=1)
df = df.drop(columns=['Gender','Geography'],axis=1)
df = df.dropna()
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Male,Germany,Spain
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,True,False,False
9996,516,35,10,57369.61,1,1,1,101699.77,0,True,False,False
9997,709,36,7,0.00,1,0,1,42085.58,1,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,True,True,False
9999,792,28,4,130142.79,1,1,0,38190.78,0,False,False,False

In [6]:
x = df.drop(['Exited'],axis=1)
y = df['Exited']

In [8]:
from sklearn.preprocessing import StandardScaler 

sc = StandardScaler()
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [-0.44003595,  0.19816383, -1.38753759, ..., -1.09598752,
        -0.57873591,  1.74273971],
       [-1.53679418,  0.29351742,  1.03290776, ..., -1.09598752,
        -0.57873591, -0.57380915],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -1.09598752,
        -0.57873591, -0.57380915],
       [ 1.25683526,  0.29351742, -0.69598177, ...,  0.91241915,
         1.72790383, -0.57380915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -1.09598752,
        -0.57873591, -0.57380915]])

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y,test_size=0.3,random_state=42)

In [10]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\python37\lib\site-packages (2.14.0)
Requirement already satisfied: tensorflow-intel==2.14.0 in c:\python37\lib\site-packages (from tensorflow) (2.14.0)
Requirement already satisfied: ml-dtypes==0.2.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (3.10.0)
Requirement already satisfied: six>=1.12.0 in c:\users\sarthak\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.16.0)
Requirement already satisfied: google-pasta>=0.1.1 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (16.0.6)
Requirement already satisfied: setuptools in c:\users\sarthak\appdata\roaming\python\python310\site-packages (from tensorflow-intel==2.14.0->tensorflow) (60.9.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (0.31.0)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (0.5.4)
Requirement already satisfied: astunparse>=1.6.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (23.5.26)
Requirement already satisfied: absl-py>=1.0.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.0.0)
Requirement already satisfied: tensorflow-estimator<2.15,>=2.14.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.14.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (4.24.4)
Requirement already satisfied: packaging in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (23.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.59.0)
Requirement already satisfied: keras<2.15,>=2.14.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.14.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.14.1)
Requirement already satisfied: numpy>=1.23.5 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (1.24.3)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (3.3.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.2.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (4.5.0)
Requirement already satisfied: tensorboard<2.15,>=2.14 in c:\python37\lib\site-packages (from tensorflow-intel==2.14.0->tensorflow) (2.14.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\python37\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.14.0->tensorflow) (0.38.4)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\python37\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (0.7.1)
Requirement already satisfied: google-auth-oauthlib<1.1,>=0.5 in c:\python37\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (1.0.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\python37\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2.23.3)
Requirement already satisfied: markdown>=2.6.8 in c:\python37\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.5)
Requirement already satisfied: werkzeug>=1.0.1 in c:\python37\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2.3.4)
Requirement already satisfied: requests<3,>=2.21.0 in c:\python37\lib\site-packages (from tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2.28.2)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\python37\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (5.3.1)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\python37\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\python37\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (0.3.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\python37\lib\site-packages (from google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (1.3.1)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in c:\python37\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (0.5.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python37\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\python37\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\python37\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in c:\python37\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.4)
Requirement already satisfied: oauthlib>=3.0.0 in c:\python37\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<1.1,>=0.5->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (3.2.2)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\python37\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.15,>=2.14->tensorflow-intel==2.14.0->tensorflow) (2.1.2)

WARNING: You are using pip version 21.2.4; however, version 24.3.1 is available.
You should consider upgrading via the 'C:\python37\python.exe -m pip install --upgrade pip' command.

In [11]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [12]:
model = Sequential()
model.add(Dense(activation='relu',units=6))
model.add(Dense(activation='relu',units=6))
model.add(Dense(activation='sigmoid',units=1))
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,batch_size=10,epochs=50)

Epoch 1/50
700/700 [==============================] - 5s 3ms/step - loss: 0.5324 - accuracy: 0.7884
Epoch 2/50
700/700 [==============================] - 2s 4ms/step - loss: 0.4634 - accuracy: 0.7924
Epoch 3/50
700/700 [==============================] - 3s 4ms/step - loss: 0.4437 - accuracy: 0.7924
Epoch 4/50
700/700 [==============================] - 2s 2ms/step - loss: 0.4348 - accuracy: 0.7981
Epoch 5/50
700/700 [==============================] - 2s 3ms/step - loss: 0.4279 - accuracy: 0.8094
Epoch 6/50
700/700 [==============================] - 2s 3ms/step - loss: 0.4204 - accuracy: 0.8209
Epoch 7/50
700/700 [==============================] - 3s 4ms/step - loss: 0.4134 - accuracy: 0.8261
Epoch 8/50
700/700 [==============================] - 4s 5ms/step - loss: 0.4067 - accuracy: 0.8276
Epoch 9/50
700/700 [==============================] - 3s 5ms/step - loss: 0.4007 - accuracy: 0.8320
Epoch 10/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3946 - accuracy: 0.8354
Epoch 11/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3893 - accuracy: 0.8371
Epoch 12/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3849 - accuracy: 0.8401
Epoch 13/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3812 - accuracy: 0.8419
Epoch 14/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3780 - accuracy: 0.8439
Epoch 15/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3745 - accuracy: 0.8431
Epoch 16/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3715 - accuracy: 0.8473
Epoch 17/50
700/700 [==============================] - 4s 5ms/step - loss: 0.3693 - accuracy: 0.8499
Epoch 18/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3666 - accuracy: 0.8496
Epoch 19/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3644 - accuracy: 0.8523
Epoch 20/50
700/700 [==============================] - 4s 5ms/step - loss: 0.3625 - accuracy: 0.8509
Epoch 21/50
700/700 [==============================] - 4s 6ms/step - loss: 0.3605 - accuracy: 0.8534
Epoch 22/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3589 - accuracy: 0.8540
Epoch 23/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3572 - accuracy: 0.8536
Epoch 24/50
700/700 [==============================] - 4s 5ms/step - loss: 0.3554 - accuracy: 0.8573
Epoch 25/50
700/700 [==============================] - 4s 5ms/step - loss: 0.3544 - accuracy: 0.8553
Epoch 26/50
700/700 [==============================] - 3s 5ms/step - loss: 0.3525 - accuracy: 0.8557
Epoch 27/50
700/700 [==============================] - 3s 4ms/step - loss: 0.3511 - accuracy: 0.8569
Epoch 28/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3496 - accuracy: 0.8573
Epoch 29/50
700/700 [==============================] - 2s 4ms/step - loss: 0.3488 - accuracy: 0.8590
Epoch 30/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3473 - accuracy: 0.8569
Epoch 31/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3470 - accuracy: 0.8586
Epoch 32/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3464 - accuracy: 0.8586
Epoch 33/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3450 - accuracy: 0.8591
Epoch 34/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3447 - accuracy: 0.8610
Epoch 35/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3446 - accuracy: 0.8596
Epoch 36/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3435 - accuracy: 0.8584
Epoch 37/50
700/700 [==============================] - 2s 4ms/step - loss: 0.3429 - accuracy: 0.8596
Epoch 38/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3433 - accuracy: 0.8600
Epoch 39/50
700/700 [==============================] - 3s 4ms/step - loss: 0.3423 - accuracy: 0.8619
Epoch 40/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3416 - accuracy: 0.8627
Epoch 41/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3414 - accuracy: 0.8600
Epoch 42/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3409 - accuracy: 0.8600
Epoch 43/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3407 - accuracy: 0.8624
Epoch 44/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3399 - accuracy: 0.8616
Epoch 45/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3404 - accuracy: 0.8609
Epoch 46/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3405 - accuracy: 0.8617
Epoch 47/50
700/700 [==============================] - 2s 4ms/step - loss: 0.3403 - accuracy: 0.8609
Epoch 48/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3392 - accuracy: 0.8623
Epoch 49/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3395 - accuracy: 0.8629
Epoch 50/50
700/700 [==============================] - 2s 3ms/step - loss: 0.3396 - accuracy: 0.8600

In [13]:
y_pred = model.predict(x_test)
y_pred = (y_pred > 0.5).astype(int)
y_pred

94/94 [==============================] - 0s 1ms/step

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [0]])

In [14]:
from sklearn.metrics import accuracy_score, confusion_matrix
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.8693333333333333
[[2318   98]
 [ 294  290]]